### ISSUE TITLE
UIBarButtonItem badge

### ISSUE THREAD

**Issue by najdan** [Minitour/EasyNotificationBadge#12]
**Description**
I've tried to set badge to `UIBarButtonItem` but badge is not visible.

Code I've used
```swift
let filterButton = UIBarButtonItem(image: #imageLiteral(resourceName: "filter"),
								   style: .plain,
								   target: self,
								   action: nil)
filterButton.tintColor = .primary
filterButton.badge(text: "2")
```

![image](https://user-images.githubusercontent.com/4264802/53292265-283f5b00-37c0-11e9-8db7-02fe4daed3f0.png)

---
**Workaround**
Instead of creating UIBarButtonItem with image create it using `customView` constructor
```swift
let filterButton = UIBarButtonItem(customView: UIImageView(image: #imageLiteral(resourceName: "filter")))
filterButton.tintColor = .primary
filterButton.action = #selector(filter(_:))
filterButton.customView?.badge(text: "2")
navigationItem.rightBarButtonItem = filterButton
```

---

Thanks for great lightweight library.

_Best regards,_
_**Najdan**_

**Comment by Minitour** [comment]
@Najdan Thanks for the suggestion!

The main problem with the badge is that the view must be rendered in order to add the badge to it. Have you tried adding the badge after the view has loaded?

**Comment by najdan** [comment]
@Minitour I've tried to set it up `viewDidLoad()` and it didn't work. But if I create `UIBarButtonItem` as lazy property and use `badge` on it later it works as expected. `UIBarButtonItem` is a bit weird, had problems with action as well, it wasn't triggered until I moved it to lazy property.

I'll close this issue since badge works after view is correctly loaded.

Thanks a lot for fast answer.
