### ISSUE TITLE
Not able to add through swift package manager using tag 1.2.0

### ISSUE THREAD

**Issue by AalokParikh** [Minitour/EasyNotificationBadge#17]
![Screen Shot 2020-10-22 at 4 46 26 PM](https://user-images.githubusercontent.com/1628260/96864701-77063200-1486-11eb-9f68-566a1d1edf50.png)
It gives error that no package.swift file is available for 1.2.0.

**Comment by AalokParikh** [comment]
![Uploading Screen Shot 2020-10-22 at 4.46.26 PM.png…]()

**Comment by Minitour** [comment]
I don't use package manager so I am not really sure what the issue is. @afnanm1999 maybe you know?

**Comment by AalokParikh** [comment]
I got it.
Issue is the tag 1.2.0 did not contain the Package.swift file even though the master branch do have it.

Please update that and all is set, for now we can access it through master branch.

**Comment by Minitour** [comment]
I created a new tag `1.2.1`. Try to use it instead.

**Comment by jsm174** [comment]
@Minitour - Could you please bump the cocoapods version as well? The font support from #10 would be super helpful.

**Comment by Minitour** [comment]
@jsm174 This completely went over my head. I bumped the version to 1.2.2.
