### ISSUE TITLE
Badge's views appearing below.

### ISSUE THREAD

**Issue by lukeleleh** [Minitour/EasyNotificationBadge#7]
Badges appear correctly first time.

However, the problem happens when you return from a pushed UIViewController from NavigationViewController.

![screen shot 2017-11-22 at 4 24 38 pm](https://user-images.githubusercontent.com/18327422/33135091-b927539e-cfa1-11e7-8729-3a798dab958c.png)

Only happens in devices running iOS 11 [Xcode 9.1]. 

Thank you for the library 😁

**Comment by Minitour** [comment]
Please elaborate

**Comment by lukeleleh** [comment]
I've attached you the project.
[Badge issue example.zip](https://github.com/Minitour/EasyNotificationBadge/files/1496624/Badge.issue.example.zip)

The problem:
![1](https://user-images.githubusercontent.com/18327422/33136481-996c7b5c-cfa5-11e7-88da-9a354526aaee.gif)

**Comment by Minitour** [comment]
Thanks for reporting @LukA888. I will look into it.

**Comment by Minitour** [comment]
@LukA888 
Fixed with the release of `1.1.3`.

**Comment by lukeleleh** [comment]
Thank you @Minitour 😄
