### ISSUE TITLE
Issue with CollectionViewCell

### ISSUE THREAD

**Issue by toseefkhilji** [Minitour/EasyNotificationBadge#9]
I am facing issue in  CollectionViewCell.

![screen shot 2018-08-21 at 4 18 26 pm](https://user-images.githubusercontent.com/2367614/44397464-0f7a9200-a55e-11e8-8bab-7e2e40130b24.png)

**Comment by Minitour** [comment]
@toseefkhilji 
It is happening because you have `masksToBounds` set to true.
Either disable the mask to bounds, or put your view which has `masksToBounds` enabled in another view, to which you will add the badge.

**Comment by toseefkhilji** [comment]
@Minitour 👍
